(()=>{
  const TOOL_PATH='/tools/wuwa-echo-calculator/?embed=blog';
  const ROOT_ID='wuwa-toolbox-root',FRAME_ID='wuwa-calculator-frame';
  const isWuwa=()=>/^\/wuwa\/?$/.test(location.pathname);
  const tv=(n,f)=>getComputedStyle(document.documentElement).getPropertyValue(n).trim()||f;
  function themeCss(){const dark=document.documentElement.dataset.theme==='dark',main=tv('--anzhiyu-main','#425AEF'),card=tv('--anzhiyu-card-bg',dark?'#1d1e20':'#fff'),soft=tv('--anzhiyu-secondbg',dark?'#242629':'#f7f9fe'),text=tv('--anzhiyu-fontcolor',dark?'#f1f1f1':'#363636'),muted=tv('--anzhiyu-secondtext',dark?'#aaa':'#858585'),border=tv('--anzhiyu-card-border',dark?'rgba(255,255,255,.1)':'rgba(60,60,67,.12)');return `:root{--bg:transparent!important;--panel:${card}!important;--panel2:${soft}!important;--line:${border}!important;--text:${text}!important;--muted:${muted}!important;--accent:${main}!important;--accent2:${main}!important;--shadow:none!important;color-scheme:${dark?'dark':'light'}}html,body{background:transparent!important}.wrap{width:100%!important;max-width:none!important}.main-grid{padding:14px!important;gap:14px!important}.panel{border-radius:14px!important;box-shadow:none!important}.step{background:color-mix(in srgb,${main} 12%,transparent)!important;color:${main}!important}button.primary{background:${main}!important;border-color:${main}!important;color:#fff!important}.mode-card.active{border-color:${main}!important}.character-card:hover,.character-pick:hover{border-color:${main}!important}.callout,.metric-card.accent{background:color-mix(in srgb,${main} ${dark?'10%':'7%'},${card})!important;border-color:${main}!important}a,.bar-value,.coverage-item b{color:${main}!important}.bar-fill{background:${main}!important}@media(max-width:620px){.main-grid{padding:8px!important}}`;}
  function sync(frame){try{const d=frame.contentDocument;if(!d?.head)return;let s=d.getElementById('wuwa-blog-embed-theme');if(!s){s=d.createElement('style');s.id='wuwa-blog-embed-theme';d.head.appendChild(s)}s.textContent=themeCss()}catch(e){}}
  function autoHeight(frame){const resize=()=>{try{const d=frame.contentDocument;if(!d)return;frame.style.height=Math.max(d.body?.scrollHeight||0,d.documentElement?.scrollHeight||0,720)+6+'px'}catch(e){frame.style.height='5200px'}};try{const d=frame.contentDocument;if(!d)return;new ResizeObserver(resize).observe(d.documentElement);new MutationObserver(resize).observe(d.body||d.documentElement,{childList:true,subtree:true,attributes:true});resize();setTimeout(resize,250);setTimeout(resize,900)}catch(e){resize()}}
  const html=()=>`<div class="wuwa-toolbox-hero"><div class="wuwa-toolbox-kicker">鸣潮工具箱 · Theory Lab</div><h2>声骸边际收益计算器</h2><p>默认只计算声骸本身的边际收益；需要研究配队时，再主动开启高级模式加入队友 Buff 与输出窗口。</p><div class="wuwa-toolbox-tags"><span class="wuwa-toolbox-tag">角色卡片选择</span><span class="wuwa-toolbox-tag">副词条边际收益</span><span class="wuwa-toolbox-tag">稀释边界</span><span class="wuwa-toolbox-tag">可选高级配队</span></div><div class="wuwa-toolbox-meta"><span>角色库：库街区《鸣潮》WIKI</span><span>交互参考：<a href="https://wuwacalc.cn" target="_blank" rel="noreferrer">wuwacalc.cn</a> · 南边道友TEIO</span></div></div><section class="wuwa-tool-shell"><div class="wuwa-tool-shell-head"><div class="wuwa-tool-title"><strong>Echo Marginal Calculator</strong><span>普通模式不要求 Buff 覆盖或输出窗口；高级功能由玩家自行开启。</span></div><div class="wuwa-tool-actions"><a href="https://github.com/etg227/etg227.github.io/tree/main/tools/wuwa-echo-calculator" target="_blank" rel="noreferrer">源码 / Reference</a></div></div><div class="wuwa-tool-embed-wrap"><div class="wuwa-tool-loading" id="wuwa-tool-loading"><span class="wuwa-tool-loading-dot"></span>正在载入计算引擎…</div><iframe id="${FRAME_ID}" title="鸣潮声骸边际收益计算器" src="${TOOL_PATH}" loading="eager"></iframe></div></section>`;
  function mount(){if(!isWuwa()){document.body?.classList.remove('wuwa-toolbox-mounted');return}const c=document.getElementById('article-container');if(!c)return;document.body.classList.add('wuwa-toolbox-mounted');let root=document.getElementById(ROOT_ID);if(!root){root=document.createElement('div');root.id=ROOT_ID;root.innerHTML=html();c.prepend(root)}const f=document.getElementById(FRAME_ID);if(!f||f.dataset.bound)return;f.dataset.bound='1';f.addEventListener('load',()=>{sync(f);autoHeight(f);document.getElementById('wuwa-tool-loading')?.classList.add('is-ready')})}
  window.mountWuwaToolbox=mount;new MutationObserver(()=>{const f=document.getElementById(FRAME_ID);if(f)sync(f)}).observe(document.documentElement,{attributes:true,attributeFilter:['data-theme']});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();document.addEventListener('pjax:complete',()=>setTimeout(mount,0));
})();
